name: dailygrocer_mobile
description: Daily Grocer — premium mobile storefront.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
