"""phase_1_model_enrichment

Revision ID: 09d6e000f8d2
Revises: b2c3d4e5f6a7
Create Date: 2026-04-12 20:56:52.422192
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '09d6e000f8d2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('customers', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('referred_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_referral_code'), 'customers', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'customers', 'customers', ['referred_by'], ['id'], ondelete='SET NULL')
    op.add_column('order_items', sa.Column('is_substituted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('order_items', sa.Column('substituted_product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'products', ['substituted_product_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('order_type', sa.String(length=20), nullable=False, server_default='delivery'))
    op.add_column('orders', sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('coupon_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('rejected_reason', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('member_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('promo_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('promo_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('promo_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('is_age_restricted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('age_restriction_type', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('nutritional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('weight_unit', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('calories_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('stores', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('store_type', sa.String(length=50), nullable=True))
    op.add_column('stores', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('stores', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.add_column('stores', sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('stores', sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('stores', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('stores', sa.Column('default_delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='1.99'))
    op.add_column('stores', sa.Column('free_delivery_threshold', sa.Numeric(precision=10, scale=2), nullable=False, server_default='30.00'))
    op.add_column('stores', sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=False, server_default='10.00'))
    op.add_column('stores', sa.Column('avg_prep_time_min', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('stores', sa.Column('is_open', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('stores', sa.Column('temporarily_closed_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_column('stores', 'temporarily_closed_reason')
    op.drop_column('stores', 'is_open')
    op.drop_column('stores', 'avg_prep_time_min')
    op.drop_column('stores', 'min_order_value')
    op.drop_column('stores', 'free_delivery_threshold')
    op.drop_column('stores', 'default_delivery_fee')
    op.drop_column('stores', 'opening_hours')
    op.drop_column('stores', 'lng')
    op.drop_column('stores', 'lat')
    op.drop_column('stores', 'banner_url')
    op.drop_column('stores', 'logo_url')
    op.drop_column('stores', 'description')
    op.drop_column('stores', 'store_type')
    op.drop_column('stores', 'slug')
    op.drop_column('products', 'calories_per_100g')
    op.drop_column('products', 'weight_unit')
    op.drop_column('products', 'nutritional_info')
    op.drop_column('products', 'allergens')
    op.drop_column('products', 'age_restriction_type')
    op.drop_column('products', 'is_age_restricted')
    op.drop_column('products', 'promo_end')
    op.drop_column('products', 'promo_start')
    op.drop_column('products', 'promo_price')
    op.drop_column('products', 'member_price')
    op.drop_column('orders', 'rejected_reason')
    op.drop_column('orders', 'dispatched_at')
    op.drop_column('orders', 'picked_at')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'coupon_id')
    op.drop_column('orders', 'tip_amount')
    op.drop_column('orders', 'service_fee')
    op.drop_column('orders', 'order_type')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'substituted_product_id')
    op.drop_column('order_items', 'is_substituted')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_referral_code'), table_name='customers')
    op.drop_column('customers', 'referred_by')
    op.drop_column('customers', 'referral_code')
    op.drop_column('customers', 'wallet_balance')
    op.drop_column('customers', 'dob')
    # ### end Alembic commands ###
