"""phase3_schema_additions

Revision ID: 17e7025c9862
Revises: c2b2f7df6f69
Create Date: 2026-04-17 22:27:34.586431
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '17e7025c9862'
down_revision: Union[str, None] = 'c2b2f7df6f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_coupon_redemptions_composite', table_name='coupon_redemptions')
    op.drop_index('idx_spend_composite', table_name='customer_monthly_spends')
    op.drop_index('idx_customers_org', table_name='customers')
    op.drop_index('idx_order_items_product', table_name='order_items')
    op.add_column('orders', sa.Column('cancel_window_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('scheduled_delivery_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('scheduled_delivery_end', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_index('idx_orders_status_store', table_name='orders')
    op.drop_column('orders', 'subtotal')
    op.drop_index('ix_postcode_zone_mappings_postcode', table_name='postcode_zone_mappings')
    op.create_index(op.f('ix_postcode_zone_mappings_postcode'), 'postcode_zone_mappings', ['postcode'], unique=True)
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_products_search', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('stores', sa.Column('surge_multiplier', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('stores', sa.Column('is_surge_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_surge_active')
    op.drop_column('stores', 'surge_multiplier')
    op.drop_index('ix_products_search', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'search_vector')
    op.drop_index(op.f('ix_postcode_zone_mappings_postcode'), table_name='postcode_zone_mappings')
    op.create_index('ix_postcode_zone_mappings_postcode', 'postcode_zone_mappings', ['postcode'], unique=False)
    op.add_column('orders', sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.create_index('idx_orders_status_store', 'orders', ['store_id', 'status'], unique=False)
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.drop_column('orders', 'scheduled_delivery_end')
    op.drop_column('orders', 'scheduled_delivery_start')
    op.drop_column('orders', 'cancel_window_expires_at')
    op.create_index('idx_order_items_product', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_customers_org', 'customers', ['organization_id'], unique=False)
    op.create_index('idx_spend_composite', 'customer_monthly_spends', ['customer_id', 'store_id', 'year_month'], unique=True)
    op.create_index('idx_coupon_redemptions_composite', 'coupon_redemptions', ['coupon_id', 'customer_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
