"""add sale_type to sales

Revision ID: 180545d32067
Revises: 8f5c45bc5e6b
Create Date: 2026-02-22 08:00:13.996949
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '180545d32067'
down_revision: Union[str, None] = '8f5c45bc5e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_type', sa.String(length=50), server_default='regular', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_type')
    # ### end Alembic commands ###
