"""phase_3_rewards

Revision ID: 3ae55c30ff6f
Revises: 61a0fafb80f7
Create Date: 2026-04-12 23:02:21.308574
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3ae55c30ff6f'
down_revision: Union[str, None] = '61a0fafb80f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_monthly_spends',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('spend_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_monthly_spends_customer_id'), 'customer_monthly_spends', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_monthly_spends_store_id'), 'customer_monthly_spends', ['store_id'], unique=False)
    op.create_index(op.f('ix_customer_monthly_spends_year_month'), 'customer_monthly_spends', ['year_month'], unique=False)
    op.create_table('rewards_tiers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_events',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['rewards_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_events')
    op.drop_table('rewards_tiers')
    op.drop_index(op.f('ix_customer_monthly_spends_year_month'), table_name='customer_monthly_spends')
    op.drop_index(op.f('ix_customer_monthly_spends_store_id'), table_name='customer_monthly_spends')
    op.drop_index(op.f('ix_customer_monthly_spends_customer_id'), table_name='customer_monthly_spends')
    op.drop_table('customer_monthly_spends')
    # ### end Alembic commands ###
