"""Add preorders

Revision ID: 8f5c45bc5e6b
Revises: 
Create Date: 2026-02-22 06:32:10.550064
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8f5c45bc5e6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('deposit_paid', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('preorder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_preorder_id'), 'sales', ['preorder_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'preorders', ['preorder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_preorder_id'), table_name='sales')
    op.drop_column('sales', 'preorder_id')
    op.drop_column('sales', 'deposit_paid')
    # ### end Alembic commands ###
