"""add_extended_product_details

Revision ID: 9262882f5de6
Revises: 9e86745a8926
Create Date: 2026-05-10 00:31:35.017588
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '9262882f5de6'
down_revision: Union[str, None] = '9e86745a8926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('safety_statements', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('allergy_advice', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('product_marketing', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('storage_type', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('country_of_origin', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('alcohol_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('company_address', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('manufacturer_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('disclaimer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'disclaimer')
    op.drop_column('products', 'manufacturer_name')
    op.drop_column('products', 'company_address')
    op.drop_column('products', 'company_name')
    op.drop_column('products', 'alcohol_data')
    op.drop_column('products', 'country_of_origin')
    op.drop_column('products', 'storage_type')
    op.drop_column('products', 'features')
    op.drop_column('products', 'product_marketing')
    op.drop_column('products', 'allergy_advice')
    op.drop_column('products', 'safety_statements')
    # ### end Alembic commands ###
