"""auto_migration

Revision ID: 9e86745a8926
Revises: cf5777792362
Create Date: 2026-04-28 13:12:49.707578
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9e86745a8926'
down_revision: Union[str, None] = 'cf5777792362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_charge_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('refund_items', sa.Column('customer_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_items', 'customer_notes')
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'stripe_charge_id')
    # ### end Alembic commands ###
