"""implement granular refund system tables and columns

Revision ID: cf5777792362
Revises: d6545cd412a3
Create Date: 2026-04-19 22:04:59.545496
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'cf5777792362'
down_revision: Union[str, None] = 'd6545cd412a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_status_history_refund_id', table_name='refund_status_history')
    op.drop_index('ix_refund_status_history_refund_item_id', table_name='refund_status_history')
    op.drop_table('refund_status_history')
    op.drop_index('ix_refund_evidence_refund_item_id', table_name='refund_evidence')
    op.drop_table('refund_evidence')
    op.add_column('order_items', sa.Column('effective_unit_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('refunded_quantity', sa.Numeric(precision=10, scale=3), nullable=False, server_default='0'))
    
    # Backfill effective_unit_price
    op.execute('UPDATE order_items SET effective_unit_price = unit_price WHERE effective_unit_price IS NULL')
    op.add_column('refund_items', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('refund_items', sa.Column('requires_manual_review', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('refund_items', 'reason',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_refund_items_reviewed_by', table_name='refund_items')
    op.drop_index('ix_refund_items_status', table_name='refund_items')
    op.create_index('ix_refund_items_composite_lookup', 'refund_items', ['order_item_id', 'status'], unique=False)
    op.create_index('ix_refund_items_pending_unique', 'refund_items', ['order_item_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.drop_constraint('refund_items_reviewed_by_fkey', 'refund_items', type_='foreignkey')
    op.drop_constraint('refund_items_order_item_id_fkey', 'refund_items', type_='foreignkey')
    op.create_foreign_key(None, 'refund_items', 'order_items', ['order_item_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('refund_items', 'customer_note')
    op.drop_column('refund_items', 'reviewed_at')
    op.drop_column('refund_items', 'reviewed_by')
    op.drop_column('refund_items', 'admin_note')
    op.add_column('refunds', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('refunds', sa.Column('destination', sa.String(length=20), nullable=False, server_default='wallet'))
    
    # Preserve legacy amounts
    op.execute('UPDATE refunds SET total_amount = amount')
    op.drop_column('refunds', 'amount')
    op.drop_column('refunds', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False, server_default='Migrated'))
    op.add_column('refunds', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default='0'))
    op.drop_column('refunds', 'destination')
    op.drop_column('refunds', 'total_amount')
    op.add_column('refund_items', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refund_items', sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('refund_items', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('refund_items', sa.Column('customer_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refund_items', type_='foreignkey')
    op.create_foreign_key('refund_items_order_item_id_fkey', 'refund_items', 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('refund_items_reviewed_by_fkey', 'refund_items', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_refund_items_pending_unique', table_name='refund_items', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_refund_items_composite_lookup', table_name='refund_items')
    op.create_index('ix_refund_items_status', 'refund_items', ['status'], unique=False)
    op.create_index('ix_refund_items_reviewed_by', 'refund_items', ['reviewed_by'], unique=False)
    op.alter_column('refund_items', 'reason',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('refund_items', 'requires_manual_review')
    op.drop_column('refund_items', 'admin_notes')
    op.drop_column('order_items', 'refunded_quantity')
    op.drop_column('order_items', 'effective_unit_price')
    op.create_table('refund_evidence',
    sa.Column('refund_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refund_item_id'], ['refund_items.id'], name='refund_evidence_refund_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refund_evidence_pkey')
    )
    op.create_index('ix_refund_evidence_refund_item_id', 'refund_evidence', ['refund_item_id'], unique=False)
    op.create_table('refund_status_history',
    sa.Column('refund_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refund_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='refund_status_history_changed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name='refund_status_history_refund_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_item_id'], ['refund_items.id'], name='refund_status_history_refund_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refund_status_history_pkey')
    )
    op.create_index('ix_refund_status_history_refund_item_id', 'refund_status_history', ['refund_item_id'], unique=False)
    op.create_index('ix_refund_status_history_refund_id', 'refund_status_history', ['refund_id'], unique=False)
    # ### end Alembic commands ###
