"""phase_2_coupons

Revision ID: f95fb0b1a305
Revises: 09d6e000f8d2
Create Date: 2026-04-12 22:44:26.715986
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f95fb0b1a305'
down_revision: Union[str, None] = '09d6e000f8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
