class AuditAction:
    # Auth
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_PASSWORD_CHANGED = "AUTH_PASSWORD_CHANGED"
    AUTH_TOKEN_REFRESHED = "AUTH_TOKEN_REFRESHED"

    # Sales
    SALE_CREATED = "SALE_CREATED"
    SALE_VOIDED = "SALE_VOIDED"
    SALE_REFUNDED = "SALE_REFUNDED"
    SALE_DISCOUNT_APPLIED = "SALE_DISCOUNT_APPLIED"

    # Inventory
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    STOCK_TRANSFERRED = "STOCK_TRANSFERRED"
    STOCK_TRANSFER_APPROVED = "STOCK_TRANSFER_APPROVED"
    STOCK_TAKEN = "STOCK_TAKEN"

    # Products
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"

    # Pre-Orders
    PREORDER_CREATED = "PREORDER_CREATED"
    PREORDER_UPDATED = "PREORDER_UPDATED"
    PREORDER_STATUS_CHANGED = "PREORDER_STATUS_CHANGED"
    PREORDER_CONVERTED = "PREORDER_CONVERTED"
    PREORDER_CANCELLED = "PREORDER_CANCELLED"

    # Users
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_REACTIVATED = "USER_REACTIVATED"

    # Settings
    STORE_SETTINGS_CHANGED = "STORE_SETTINGS_CHANGED"
    TAX_RATE_CHANGED = "TAX_RATE_CHANGED"
    ORG_SETTINGS_CHANGED = "ORG_SETTINGS_CHANGED"

    # Cash
    CASH_DRAWER_OPENED = "CASH_DRAWER_OPENED"
